# system configuration
system:
  httpPort: 8300

# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: ''
  database: 'account'
  username: 'root'
  password: 'root'
  maxIdleConns: 10
  maxOpenConns: 100
  logMode: false
  logZap: ""

# redis configuration
redis:
  db: 1
  addr: '127.0.0.1:6379'
  password: ''

# zap logger configuration
zap:
  level: 'info'
  format: 'json'
  prefix: '[AAA]'
  director: 'logs'
  linkName: 'latest_log'
  show-line: true
  encodeLevel: 'LowercaseLevelEncoder'
  stacktraceKey: 'stacktrace'
  logInConsole: true
  filepath: 'storage/logs'

# jwt
JWT:
#  secret: ainiok
#  issuer: api-service
  expire: 7200